### ISSUE TITLE
Panic error in localexec

### ISSUE THREAD

**Issue by drano** [tilt-dev/tilt#4841]
My tiltfile worked until yesterday, but, now, I have a panic error.

`panic: runtime error: slice bounds out of range [1:0]

goroutine 635 [running]:
github.com/tilt-dev/tilt/internal/localexec.(*Env).ExecCmd(0xc00000b8c0, 0x0, 0x0, 0x0, 0xc00242be40, 0x3f, 0x0, 0x0, 0x0, 0x34c61e8, ...)
/root/project/internal/localexec/localexec.go:59 +0x113
github.com/tilt-dev/tilt/internal/tiltfile.(*tiltfileState).execLocalCmd(0xc00084ad80, 0xc0007ae960, 0x0, 0x0, 0x0, 0xc00242be40, 0x3f, 0x0, 0x0, 0x0, ...)
/root/project/internal/tiltfile/files.go:87 +0x16c
github.com/tilt-dev/tilt/internal/tiltfile.(*tiltfileState).local(0xc00084ad80, 0xc0007ae960, 0xc0017d3ad0, 0xc0026ee5a0, 0x1, 0x1, 0xc001b88c80, 0x5, 0x5, 0x34dbb78, ...)
/root/project/internal/tiltfile/files.go:59 +0x498`

In my browser web, I can see the last message from tiltfile:
`Running: helm template solr-operator D:\Sources\Products\QuartzX.Organization\.helm\apache-solr\0.3.0\solr-operator --include-crds --namespace default --set zookeeper-operator.crd.create=true --set replicaCount=2 --set zookeeper-operator.replicaCount=1`

In my tiltfile, I have

`    helm_remote(
	    'solr-operator',
	    repo_url='https://solr.apache.org/charts', 
	    repo_name='apache-solr',
        version='0.3.0',
        set=['zookeeper-operator.crd.create=true',
             'replicaCount=2',
             'zookeeper-operator.replicaCount=1'])`

**Comment by landism** [comment]
- IIUC, this is caused by an empty cmd in `local` and the `helm_remote` is a red herring (i.e., that's the last thing Tilt did before it hit the problematic cmd)
- This should fix the change that broke things for you: https://github.com/tilt-dev/tilt-extensions/pull/222
- This fixes Tilt panicking on empty cmds: https://github.com/tilt-dev/tilt/pull/4842

**Comment by drano** [comment]
Thanks !
