### ISSUE TITLE
fsnotify/windows - Out of range error when file path length exceeds 260 characters

### ISSUE THREAD

**Issue by SimonPedley** [tilt-dev/tilt#5835]
### Expected Behavior
Tilt watches the code files that have long file paths (more than 260 characters) without erroring.

### Current Behavior
The Tilt process fatally crashes with the following error:
```
panic: runtime error: slice bounds out of range [:303] with length 260

goroutine 1836 [running, locked to thread]:
github.com/tilt-dev/fsnotify.(*Watcher).readEvents(0xc0019ade00)
        /root/project/vendor/github.com/tilt-dev/fsnotify/windows.go:507 +0xd0f
created by github.com/tilt-dev/fsnotify.NewWatcher
        /root/project/vendor/github.com/tilt-dev/fsnotify/windows.go:53 +0x1e5
panic: runtime error: slice bounds out of range [:303] with length 260

goroutine 1614 [running, locked to thread]:
github.com/tilt-dev/fsnotify.(*Watcher).readEvents(0xc00196ceb0)
        /root/project/vendor/github.com/tilt-dev/fsnotify/windows.go:507 +0xd0f
created by github.com/tilt-dev/fsnotify.NewWatcher
        /root/project/vendor/github.com/tilt-dev/fsnotify/windows.go:53 +0x1e5
```

### Steps to Reproduce
1. Ensure you have long file paths enabled in windows by setting the following registry key to `1`: `HKLM\SYSTEM\CurrentControlSet\Control\FileSystem`
2. If you've had to enable the key above, ensure you've restarted your device in order to update windows (Apologies for the nuisance of this)
3. Clone the following repo: `https://github.com/SimonPedley/Tilt_LongFilePathErrorExample`
4. Run the powershell script `./get-file.ps1` which will generate a file with a long path (cannot push long files to git)
5. Run `tilt up`
6. Ensure tilt is up and the single container `tilt-test` should exist and be running successfully.
7. Now modify the text file that is at the long path length.
8. Your tilt instance will fall over with the above error.

#### `tilt doctor` Output
```
Tilt: v0.30.1, built 2022-05-20
System: windows-amd64
---
Docker
- Host: [default]
- Server Version:
- API Version:
- Builder:
- Compose Version: v2.5.1
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: read-failure
- Version: v1.22.4
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 2c3c97a314700584faec486b5a0e8f5b
- Repo: yQP3vS2aLHbH7OA5w6fOUg==
```

#### About Your Use Case
We are using source generators to generate code in our codebase. The generated code is placed in quite deep paths in our codebase, which is something we cannot currently change.

The builds are absolutely fine but when those files are modified tilt falls over and the developer has to restart it every time which is time consuming and frustrating.

Technically, tilt shouldn't actually be watching these files, because they are behind `.dockerignore` (as demonstrated in the example git repo) so aren't even pulled into the image as they are generated at build. But it seems the file system watcher in fsnotify still watches the file regardless. Perhaps this code is being hit before Tilt decides that it should ignore the event.

I am not proficient in Go, but i have had a look at the code triggering the error and it appears the a filename buffer here:
https://github.com/tilt-dev/tilt/blob/4c0183278c306af373c185b0de6f21590b572ea0/vendor/github.com/tilt-dev/fsnotify/windows.go#L506
is fixed to the `syscall.MAX_PATH` instead of the file path.

Looking deeper, it appears fsnotify have actually fixed this issue in their code base here:
https://github.com/fsnotify/fsnotify/blob/0f4b979323bea7ee6677faa4a88078ec558b1b80/windows.go#L473
So it maybe a case of just updating this code as i can see it's a fork of their code?

Or perhaps, the line linked above in your code should be changed from: `buf := (*[syscall.MAX_PATH]uint16)(unsafe.Pointer(&raw.FileName))`
To:
`buf := (*[raw.FileNameLength/2]uint16)(unsafe.Pointer(&raw.FileName))`

I'm happy to try and make a change in a fork of my own to help speed along a fix. But as i say, my Go is not strong.

Thanks a lot for your help.

**Comment by SimonPedley** [comment]
Looks great, thank you!
I will raise another issue if we hit further issues.

Is there a way for me to test this?
Or when will it be released so i can verify it works?

**Comment by SimonPedley** [comment]
Just to let you know this has fixed our issue.
Thank you for your speedy turn around!
