### ISSUE TITLE
kubernetesdiscoverys.filterForResource nil pointer dereference

### ISSUE THREAD

**Issue by Davincible** [tilt-dev/tilt#5866]
I'm getting a nil pointer dereference for a Tiltfile that has previously always run fine. I'm not sure why it now stopped working.

Tilt version: `v0.30.3, built 2022-06-10`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3004156]

goroutine 1 [running]:
github.com/tilt-dev/tilt/internal/store/kubernetesdiscoverys.filterForResource(0xc00031
4380, {0xc002cea240, 0xb})
        /root/project/internal/store/kubernetesdiscoverys/reducers.go:55 +0x96
github.com/tilt-dev/tilt/internal/store/kubernetesdiscoverys.RefreshKubernetesResource(
0xc000314380, {0xc002cea240, 0xb})
        /root/project/internal/store/kubernetesdiscoverys/reducers.go:71 +0xb5
github.com/tilt-dev/tilt/internal/store/kubernetesapplys.HandleKubernetesApplyUpsertAct
ion(...)
        /root/project/internal/store/kubernetesapplys/reducers.go:11
github.com/tilt-dev/tilt/internal/engine.upperReducerFn({0x45b1270?, 0xc0008ab050?}, 0x
c000314380, {0x458a7a0?, 0xc000d2b200?})
        /root/project/internal/engine/upper.go:198 +0x116c
github.com/tilt-dev/tilt/internal/store.(*Store).Loop(0xc0004801e0, {0x45b1270?, 0xc000
8ab050?})
        /root/project/internal/store/store.go:172 +0x609
github.com/tilt-dev/tilt/internal/engine.Upper.Init({0x7f0da6c39270?}, {0x45b1270, 0xc0
008ab050}, {{0xc000053440, 0x32}, {0xc0003fae90, 0x1, 0x1}, {0xc00036aff0, 0x0, ...}, .
..})
        /root/project/internal/engine/upper.go:106 +0x9f
github.com/tilt-dev/tilt/internal/engine.Upper.Start({0xc000c53200?}, {0x45b1270, 0xc00
08ab050}, {0xc00036aff0, 0x0, 0x3}, {{0x456f5b8, 0x6}, {0x0, 0x0}, ...}, ...)
        /root/project/internal/engine/upper.go:91 +0x290
github.com/tilt-dev/tilt/internal/cli.(*upCmd).run(0xc0003407b0, {0x45b11c8?, 0xc000377
2c0?}, {0xc00036aff0, 0x0, 0x3})
        /root/project/internal/cli/up.go:168 +0x87a
github.com/tilt-dev/tilt/internal/cli.addCommand.func1(0xc0000e5b80?, {0xc00036aff0, 0x
0, 0x3})
        /root/project/internal/cli/cli.go:156 +0xb1
github.com/spf13/cobra.(*Command).execute(0xc0000e5b80, {0xc00036af90, 0x3, 0x3})
        /root/project/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e5680)
        /root/project/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /root/project/vendor/github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/project/vendor/github.com/spf13/cobra/command.go:895
github.com/tilt-dev/tilt/internal/cli.Execute()
        /root/project/internal/cli/cli.go:96 +0xece
main.main()
        /root/project/cmd/tilt/main.go:19 +0xde
```

Respective code:
https://github.com/tilt-dev/tilt/blob/81ef9ccca0e956547fcef306fbbd7cbcc90fbc91/internal/store/kubernetesdiscoverys/reducers.go#L46-L61

**Comment by nicks** [comment]
thanks for the report! ya, i think i understand the issue, should be relatively easy to fix

**Comment by Davincible** [comment]
Looking forward to having this merged :)

**Comment by nicks** [comment]
I'll do a release tomorrow since we're OOO on Friday.
