### ISSUE TITLE
panic caused by controller.go:217

### ISSUE THREAD

**Issue by diggyk** [tilt-dev/tilt#5887]
### Expected Behavior
Running `tilt up` should spin up tilt.

### Current Behavior
`tilt up` usually works just fine.  But sometimes, the system gets into a state where none of my projects will come up with `tilt`.  Instead I get this:
```
Tilt started on http://localhost:10350/
v0.30.4, built 2022-06-16

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x30ea8e0]

goroutine 1277 [running]:
github.com/tilt-dev/tilt/internal/watch.(*naiveNotify).Events(0x211347e?)
	/root/project/internal/watch/watcher_naive.go:137
github.com/tilt-dev/tilt/internal/controllers/core/filewatch.(*Controller).dispatchFileChangesLoop(0xc0004306c0, {0x45b2448, 0xc000f33e00}, 0xc000e983c0)
	/root/project/internal/controllers/core/filewatch/controller.go:225 +0x74
created by github.com/tilt-dev/tilt/internal/controllers/core/filewatch.(*Controller).addOrReplace
	/root/project/internal/controllers/core/filewatch/controller.go:217 +0x7c5
exitr@digant-dev:~/lwcode/services/weave/examples/rust$
```

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.30.4, built 2022-06-16
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.17
- API Version: 1.41
- Builder: 2
- Compose Version: v2.6.0
---
Kubernetes
- Env: kind
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: containerd
- Version: v1.23.4
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 0f353350e3d198a35b3d2ac44c2da06d
- Repo: n3Dfvc3cNe0Ephvyido45w==
```

**Comment by nicks** [comment]
thanks for reporting! i think i know what this might be, but let me poke at it a bit.
