### ISSUE TITLE
panic "assignment to entry in nil map" in 0.33.6

### ISSUE THREAD

**Issue by tot-ra** [tilt-dev/tilt#6249]
This started after upgrading tilt to 0.33.6 (from I believe 0.33.4)

### Expected Behavior
Having Tiltfile above the repo with:
```
docker_compose('./redis/docker-compose.dev.yml',project_name="gratheon")
dc_resource('redis', labels=["storage"])
```
and docker-compose - https://github.com/Gratheon/redis/blob/main/docker-compose.dev.yml

should spin up the container.. 

### Current Behavior
But instead it crashes:
```
(v1) ➜  git tilt up         
Tilt started on http://localhost:10350/
v0.33.6, built 2023-09-29

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
panic: assignment to entry in nil map

goroutine 1143 [running]:
github.com/compose-spec/compose-go/loader.projectName({{0x0, 0x0}, {0xc00185ecf0, 0x17}, {0xc0025600c0, 0x1, 0x1}, 0x0}, 0x10683dd28?)
        github.com/compose-spec/compose-go@v1.18.4/loader/loader.go:460 +0x4da
github.com/compose-spec/compose-go/loader.LoadWithContext({0x103a9c6e8, 0xc00271c640}, {{0x0, 0x0}, {0xc00185ecf0, 0x17}, {0xc0025600c0, 0x1, 0x1}, 0x0}, ...)
        github.com/compose-spec/compose-go@v1.18.4/loader/loader.go:237 +0x225
github.com/tilt-dev/tilt/internal/dockercompose.(*cmdDCClient).loadProjectCLI(0xc000331ad0?, {0x103a9c6e8, 0xc00271c640}, {{0xc0010065f0, 0x1, 0x1}, {0xc00185ecf0, 0x17}, {0x0, 0x0}, ...})
        github.com/tilt-dev/tilt/internal/dockercompose/client.go:323 +0x228
github.com/tilt-dev/tilt/internal/dockercompose.(*cmdDCClient).Project(0x1?, {0x103a9c6e8?, 0xc00271c640?}, {{0xc0010065f0, 0x1, 0x1}, {0xc00185ecf0, 0x17}, {0x0, 0x0}, ...})
        github.com/tilt-dev/tilt/internal/dockercompose/client.go:259 +0xd8
github.com/tilt-dev/tilt/internal/tiltfile.parseDCConfig({0x103a9c6e8?, 0xc00271c640?}, {0x103aa8370?, 0xc000331ad0?}, 0xc0015bb1e0)
        github.com/tilt-dev/tilt/internal/tiltfile/docker_compose.go:455 +0xbf
github.com/tilt-dev/tilt/internal/tiltfile.(*tiltfileState).dockerCompose(0xc00028b2c0, 0xc000f4ae00, 0xc001247380, {0xc0010064a0, 0x1, 0x1}, {0xc001ff9db8, 0x1, 0x1})
        github.com/tilt-dev/tilt/internal/tiltfile/docker_compose.go:166 +0xc6f
github.com/tilt-dev/tilt/internal/tiltfile/starkit.(*Environment).AddBuiltin.func1(0xc001480000?, 0x2?, {0xc0010064a0, 0x1, 0x1}, {0xc001ff9db8, 0x1, 0x1})
        github.com/tilt-dev/tilt/internal/tiltfile/starkit/environment.go:121 +0x270
go.starlark.net/starlark.(*Builtin).CallInternal(0xc0018121f0?, 0x103aa04a0?, {0xc0010064a0?, 0x10?, 0x102b59560?}, {0xc001ff9db8?, 0x24e7ae7b8?, 0x10683d3c8?})
        go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/starlark/value.go:793 +0x2b
go.starlark.net/starlark.Call(0xc000f4ae00, {0x103aa04a0?, 0xc001247380?}, {0xc0010064a0, 0x1, 0x1}, {0xc001ff9db8, 0x1, 0x1})
        go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/starlark/eval.go:1251 +0x287
go.starlark.net/starlark.(*Function).CallInternal(0xc00075b700, 0xc000f4ae00, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/starlark/interp.go:368 +0x3233
go.starlark.net/starlark.Call(0xc000f4ae00, {0x103a9f4e0?, 0xc00075b700?}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/starlark/eval.go:1251 +0x287
go.starlark.net/starlark.(*Program).Init(0xc00160a5e0?, 0x100023196?, 0x1027e56c0?)
        go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/starlark/eval.go:424 +0x59
go.starlark.net/starlark.ExecFile(0xc0002aee00?, {0xc00160a5e0, 0x1a}, {0x1027e56c0, 0xc001ff9d10}, 0xc002008780)
        go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/starlark/eval.go:352 +0xc6
github.com/tilt-dev/tilt/internal/tiltfile/starkit.(*Environment).doLoad(0xc0015082d0, 0xc002008660?, {0xc00160a5e0, 0x1a})
        github.com/tilt-dev/tilt/internal/tiltfile/starkit/environment.go:303 +0x456
github.com/tilt-dev/tilt/internal/tiltfile/starkit.(*Environment).exec(0xc0015082d0, 0xc000f4ae00, {0xc00160a5e0?, 0xc00246d708?})
        github.com/tilt-dev/tilt/internal/tiltfile/starkit/environment.go:243 +0x285
github.com/tilt-dev/tilt/internal/tiltfile/starkit.(*Environment).start(0xc0015082d0, 0xc001626580)
        github.com/tilt-dev/tilt/internal/tiltfile/starkit/environment.go:205 +0x235
github.com/tilt-dev/tilt/internal/tiltfile/starkit.ExecFile(0x1a3185c5000?, {0xc00246e4b0, 0x1b, 0xc000d26900?})
        github.com/tilt-dev/tilt/internal/tiltfile/starkit/environment.go:29 +0x171
github.com/tilt-dev/tilt/internal/tiltfile.(*tiltfileState).loadManifests(0xc00028b2c0, 0xc001626580)
        github.com/tilt-dev/tilt/internal/tiltfile/tiltfile_state.go:213 +0x3f8
github.com/tilt-dev/tilt/internal/tiltfile.tiltfileLoader.Load({0xc000142000, {0x103aa8370, 0xc000331ad0}, {0x102f4731b, 0x9}, {0x103a66480, 0xc0003f8378}, {{0xc000f19c10, 0xe}, {0x102f40f50, ...}, ...}, ...}, ...)
        github.com/tilt-dev/tilt/internal/tiltfile/tiltfile.go:179 +0x630
github.com/tilt-dev/tilt/internal/controllers/core/tiltfile.(*Reconciler).run(0xc000331c30, {0x103a9c6e8, 0xc00271c640}, {{0x0?, 0x0?}, {0xc00259a0a0?, 0xa?}}, 0xc001626580, 0xc00252c880, 0xc000af0310)
        github.com/tilt-dev/tilt/internal/controllers/core/tiltfile/reconciler.go:316 +0x3f9
created by github.com/tilt-dev/tilt/internal/controllers/core/tiltfile.(*Reconciler).startRunAsync in goroutine 1006
        github.com/tilt-dev/tilt/internal/controllers/core/tiltfile/reconciler.go:292 +0x385
        ```

```
Tilt: v0.33.6, built 2023-09-29
System: darwin-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.22
- API Version: 1.41
- Builder: 2
- Compose Version: v2.15.1
---
Kubernetes
- Env: unknown
- Context: k8s-admin
- Cluster Name: k8s-admin
- Namespace: default
- Container Runtime: containerd
- Version: v1.24.9
- Cluster Local Registry: none
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 9e6b57e87cf2e19505f06b6b7facdceb
- Repo:
```

**Comment by nicks** [comment]
can you try upgrading `compose`? with compose 2.22, i get an error - `service redis declares mutually exclusive `network_mode` and `networks`: invalid compose project`

**Comment by nicks** [comment]
filed the panic upstream as https://github.com/compose-spec/compose-go/issues/471
